# Generated by Django 4.2.5 on 2023-10-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='Listing',
        ),
    ]
